<a href="https://colab.research.google.com/github/Namratha-shankar/Fake-news-detection/blob/main/Fake_news_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [2]:
from google.colab import files
uploaded = files.upload()

Saving news.csv to news.csv

In [3]:
data = pd.read_csv("news.csv")
data.head()

,Unnamed: 0,title,text,label
0,8476,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL

In [4]:
data = data.drop(["Unnamed: 0"], axis=1)
data.head(5)

,title,text,label
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL

In [5]:
le = preprocessing.LabelEncoder()
le.fit(data['label'])
data['label'] = le.transform(data['label'])

In [6]:
embedding_dim = 50
max_length = 54
padding_type = 'post'
trunc_type = 'post'
oov_tok = "<OOV>"
training_size = 3000
test_portion = 0.1

In [7]:
title = []
text = []
labels = []
for x in range(training_size):
    title.append(data['title'][x])
    text.append(data['text'][x])
    labels.append(data['label'][x])

tokenizer1 = Tokenizer()
tokenizer1.fit_on_texts(title)
word_index1 = tokenizer1.word_index
vocab_size1 = len(word_index1)
sequences1 = tokenizer1.texts_to_sequences(title)
padded1 = pad_sequences(sequences1, padding=padding_type, truncating=trunc_type)

In [8]:
split = int(test_portion * training_size)
training_sequences1 = padded1[split:training_size]
test_sequences1 = padded1[0:split]
test_labels = labels[0:split]
training_labels = labels[split:training_size]

In [9]:
training_sequences1 = np.array(training_sequences1)
test_sequences1 = np.array(test_sequences1)

In [10]:
!wget https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
!unzip glove.6B.zip

--2026-05-10 04:28:19--  https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip’

glove.6B.zip        100%[===================>] 822.24M  5.02MB/s    in 2m 39s

2026-05-10 04:30:59 (5.16 MB/s) - ‘glove.6B.zip’ saved [862182613/862182613]

Archive:  glove.6B.zip
  inflating: glove.6B.50d.txt
  inflating: glove.6B.100d.txt
  inflating: glove.6B.200d.txt
  inflating: glove.6B.300d.txt

In [11]:
embedding_index = {}
with open('glove.6B.50d.txt', 'r', encoding='utf-8') as f:
    for line in f:
        values = line.split()
        word = values[0]
        coefs = np.asarray(values[1:], dtype='float32')
        embedding_index[word] = coefs

embedding_matrix = np.zeros((vocab_size1 + 1, embedding_dim))

for word, i in word_index1.items():
    if i < vocab_size1:
        embedding_vector = embedding_index.get(word)
        if embedding_vector is not None:
            embedding_matrix[i] = embedding_vector

In [13]:
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size1 + 1, embedding_dim,
                              input_length=max_length,
                              weights=[embedding_matrix],
                              trainable=False),

    tf.keras.layers.Dropout(0.2),

    tf.keras.layers.Conv1D(64, 5, activation='relu'),

    tf.keras.layers.MaxPooling1D(pool_size=4),

    tf.keras.layers.LSTM(64),

    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.build(input_shape=(None, max_length))

model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 54, 50)         │       377,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 54, 50)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_1 (Conv1D)               │ (None, 50, 64)         │        16,064 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_1 (MaxPooling1D)  │ (None, 12, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 64)             │        33,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 426,753 (1.63 MB)

 Trainable params: 49,153 (192.00 KB)

 Non-trainable params: 377,600 (1.44 MB)

In [14]:
history = model.fit(
    training_sequences1,
    np.array(training_labels),
    epochs=50,
    validation_data=(test_sequences1, np.array(test_labels)),
    verbose=2
)

Epoch 1/50
85/85 - 5s - 64ms/step - accuracy: 0.6289 - loss: 0.6326 - val_accuracy: 0.6833 - val_loss: 0.5621
Epoch 2/50
85/85 - 2s - 28ms/step - accuracy: 0.7130 - loss: 0.5659 - val_accuracy: 0.7133 - val_loss: 0.5019
Epoch 3/50
85/85 - 1s - 15ms/step - accuracy: 0.7419 - loss: 0.5205 - val_accuracy: 0.7300 - val_loss: 0.4971
Epoch 4/50
85/85 - 1s - 15ms/step - accuracy: 0.7681 - loss: 0.4831 - val_accuracy: 0.7667 - val_loss: 0.4702
Epoch 5/50
85/85 - 1s - 15ms/step - accuracy: 0.7930 - loss: 0.4367 - val_accuracy: 0.7300 - val_loss: 0.5044
Epoch 6/50
85/85 - 1s - 15ms/step - accuracy: 0.8067 - loss: 0.4075 - val_accuracy: 0.7633 - val_loss: 0.4883
Epoch 7/50
85/85 - 1s - 15ms/step - accuracy: 0.8456 - loss: 0.3565 - val_accuracy: 0.7767 - val_loss: 0.4792
Epoch 8/50
85/85 - 1s - 15ms/step - accuracy: 0.8681 - loss: 0.3037 - val_accuracy: 0.7133 - val_loss: 0.5852
Epoch 9/50
85/85 - 1s - 14ms/step - accuracy: 0.8822 - loss: 0.2739 - val_accuracy: 0.7433 - val_loss: 0.5140
Epoch 10/50
85/85 - 1s - 15ms/step - accuracy: 0.9019 - loss: 0.2458 - val_accuracy: 0.7100 - val_loss: 0.6427
Epoch 11/50
85/85 - 2s - 26ms/step - accuracy: 0.8863 - loss: 0.2555 - val_accuracy: 0.7700 - val_loss: 0.5299
Epoch 12/50
85/85 - 3s - 30ms/step - accuracy: 0.8993 - loss: 0.2305 - val_accuracy: 0.7333 - val_loss: 0.6022
Epoch 13/50
85/85 - 1s - 15ms/step - accuracy: 0.9181 - loss: 0.1961 - val_accuracy: 0.7533 - val_loss: 0.6240
Epoch 14/50
85/85 - 1s - 15ms/step - accuracy: 0.9211 - loss: 0.1866 - val_accuracy: 0.7667 - val_loss: 0.6717
Epoch 15/50
85/85 - 1s - 15ms/step - accuracy: 0.9296 - loss: 0.1739 - val_accuracy: 0.7533 - val_loss: 0.5797
Epoch 16/50
85/85 - 1s - 15ms/step - accuracy: 0.9319 - loss: 0.1652 - val_accuracy: 0.7567 - val_loss: 0.6924
Epoch 17/50
85/85 - 1s - 15ms/step - accuracy: 0.9426 - loss: 0.1448 - val_accuracy: 0.7900 - val_loss: 0.6492
Epoch 18/50
85/85 - 1s - 15ms/step - accuracy: 0.9444 - loss: 0.1412 - val_accuracy: 0.7900 - val_loss: 0.6690
Epoch 19/50
85/85 - 1s - 15ms/step - accuracy: 0.9422 - loss: 0.1516 - val_accuracy: 0.7867 - val_loss: 0.6245
Epoch 20/50
85/85 - 2s - 19ms/step - accuracy: 0.9559 - loss: 0.1182 - val_accuracy: 0.7767 - val_loss: 0.7146
Epoch 21/50
85/85 - 2s - 26ms/step - accuracy: 0.9504 - loss: 0.1351 - val_accuracy: 0.7800 - val_loss: 0.6245
Epoch 22/50
85/85 - 2s - 27ms/step - accuracy: 0.9459 - loss: 0.1314 - val_accuracy: 0.7400 - val_loss: 0.7533
Epoch 23/50
85/85 - 1s - 15ms/step - accuracy: 0.9507 - loss: 0.1287 - val_accuracy: 0.7767 - val_loss: 0.6099
Epoch 24/50
85/85 - 1s - 15ms/step - accuracy: 0.9559 - loss: 0.1091 - val_accuracy: 0.7700 - val_loss: 0.6679
Epoch 25/50
85/85 - 1s - 15ms/step - accuracy: 0.9659 - loss: 0.0845 - val_accuracy: 0.7467 - val_loss: 0.6902
Epoch 26/50
85/85 - 1s - 15ms/step - accuracy: 0.9626 - loss: 0.0995 - val_accuracy: 0.7667 - val_loss: 0.8124
Epoch 27/50
85/85 - 1s - 15ms/step - accuracy: 0.9644 - loss: 0.1067 - val_accuracy: 0.7600 - val_loss: 0.7319
Epoch 28/50
85/85 - 1s - 15ms/step - accuracy: 0.9670 - loss: 0.0855 - val_accuracy: 0.7700 - val_loss: 0.7577
Epoch 29/50
85/85 - 1s - 15ms/step - accuracy: 0.9659 - loss: 0.0923 - val_accuracy: 0.7633 - val_loss: 0.6592
Epoch 30/50
85/85 - 2s - 28ms/step - accuracy: 0.9674 - loss: 0.0912 - val_accuracy: 0.7700 - val_loss: 0.6794
Epoch 31/50
85/85 - 3s - 37ms/step - accuracy: 0.9633 - loss: 0.0894 - val_accuracy: 0.7267 - val_loss: 0.9062
Epoch 32/50
85/85 - 1s - 15ms/step - accuracy: 0.9552 - loss: 0.1078 - val_accuracy: 0.7633 - val_loss: 0.7456
Epoch 33/50
85/85 - 1s - 15ms/step - accuracy: 0.9707 - loss: 0.0801 - val_accuracy: 0.7333 - val_loss: 1.0263
Epoch 34/50
85/85 - 1s - 15ms/step - accuracy: 0.9644 - loss: 0.0913 - val_accuracy: 0.7933 - val_loss: 0.6189
Epoch 35/50
85/85 - 1s - 16ms/step - accuracy: 0.9604 - loss: 0.0868 - val_accuracy: 0.7733 - val_loss: 0.7085
Epoch 36/50
85/85 - 1s - 15ms/step - accuracy: 0.9752 - loss: 0.0710 - val_accuracy: 0.7800 - val_loss: 0.7332
Epoch 37/50
85/85 - 1s - 15ms/step - accuracy: 0.9730 - loss: 0.0784 - val_accuracy: 0.7833 - val_loss: 0.6782
Epoch 38/50
85/85 - 1s - 15ms/step - accuracy: 0.9693 - loss: 0.0772 - val_accuracy: 0.7300 - val_loss: 1.0149
Epoch 39/50
85/85 - 2s - 18ms/step - accuracy: 0.9696 - loss: 0.0789 - val_accuracy: 0.7733 - val_loss: 0.7310
Epoch 40/50
85/85 - 2s - 26ms/step - accuracy: 0.9663 - loss: 0.0905 - val_accuracy: 0.7833 - val_loss: 0.6614
Epoch 41/50
85/85 - 2s - 28ms/step - accuracy: 0.9807 - loss: 0.0498 - val_accuracy: 0.7867 - val_loss: 0.8985
Epoch 42/50
85/85 - 1s - 15ms/step - accuracy: 0.9733 - loss: 0.0730 - val_accuracy: 0.7767 - val_loss: 0.7954
Epoch 43/50
85/85 - 1s - 15ms/step - accuracy: 0.9778 - loss: 0.0580 - val_accuracy: 0.7867 - val_loss: 0.8206
Epoch 44/50
85/85 - 1s - 15ms/step - accuracy: 0.9696 - loss: 0.0793 - val_accuracy: 0.7833 - val_loss: 0.7592
Epoch 45/50
85/85 - 1s - 15ms/step - accuracy: 0.9781 - loss: 0.0606 - val_accuracy: 0.7567 - val_loss: 0.8724
Epoch 46/50
85/85 - 1s - 15ms/step - accuracy: 0.9737 - loss: 0.0704 - val_accuracy: 0.7667 - val_loss: 0.7184
Epoch 47/50
85/85 - 1s - 15ms/step - accuracy: 0.9811 - loss: 0.0524 - val_accuracy: 0.7800 - val_loss: 0.8433
Epoch 48/50
85/85 - 1s - 15ms/step - accuracy: 0.9700 - loss: 0.0804 - val_accuracy: 0.7567 - val_loss: 0.8845
Epoch 49/50
85/85 - 2s - 20ms/step - accuracy: 0.9774 - loss: 0.0623 - val_accuracy: 0.7900 - val_loss: 0.7203
Epoch 50/50
85/85 - 2s - 27ms/step - accuracy: 0.9785 - loss: 0.0625 - val_accuracy: 0.7700 - val_loss: 0.8387

In [15]:
X = "Karry to go to France in gesture of sympathy"

sequences = tokenizer1.texts_to_sequences([X])
sequences = pad_sequences(sequences, maxlen=max_length, padding=padding_type, truncating=trunc_type)
if model.predict(sequences, verbose=0)[0][0] >= 0.5:
    print("This news is True")
else:
    print("This news is False")

This news is False